#!/bin/sh

sed 's/.*│//g' | tr -d '\n' | grep -aEo '(((http|https|file):///*|www\.)[a-zA-Z0-9.]*[:]?[a-zA-Z0-9./&#~%?$*!=_-]*)|((magnet:\?xt=urn:btih:)[a-zA-Z0-9]*)' | sort | uniq | sed 's/^www./http:\/\/www\./g'
